[package]
name = "jmap-calendars-types"
version = "0.1.1"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JMAP Calendars extension data types (draft-ietf-jmap-calendars-*)"
keywords = ["jmap", "calendars", "types", "rfc8620"]
categories = ["encoding", "network-programming"]

[dependencies]
jmap-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
