[workspace]
members = [
    "crate-jmap-types",
    "crate-jmap-mail-types",
    "crate-jmap-chat-types",
    "crate-jmap-contacts-types",
    "crate-jmap-calendars-types",
    "crate-jmap-tasks-types",
    "crate-jmap-filenode-types",
    "crate-jmap-server",
    "crate-jmap-mail-server",
    "crate-jmap-chat-server",
    "crate-jmap-contacts-server",
    "crate-jmap-calendars-server",
    "crate-jmap-tasks-server",
    "crate-jmap-filenode-server",
    "crate-jmap-base-client",
    "crate-jmap-chat-client",
    "crate-jmap-mail-client",
    "crate-jmap-contacts-client",
    "crate-jmap-calendars-client",
    "crate-jmap-tasks-client",
    "crate-jmap-filenode-client",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.75"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
jmap-types        = { path = "crate-jmap-types" }
jmap-mail-types   = { path = "crate-jmap-mail-types" }
jmap-chat-types   = { path = "crate-jmap-chat-types" }
jmap-server       = { path = "crate-jmap-server" }
jmap-base-client  = { path = "crate-jmap-base-client" }
jmap-chat-server  = { path = "crate-jmap-chat-server" }
jmap-mail-client  = { path = "crate-jmap-mail-client" }
futures           = "0.3"
serde             = { version = "1", features = ["derive"] }
serde_json        = "1"
thiserror         = "2"
tokio             = { version = "1", features = ["rt"] }
http              = "1"
reqwest           = { version = "0.12", features = ["json", "stream", "rustls-tls-manual-roots"] }
tokio-tungstenite = { version = "0.29", features = ["rustls-tls-webpki-roots"] }
url               = "2"
