[package]
name = "jmap-tasks-types"
version = "0.1.1"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JMAP Tasks extension data types (draft-ietf-jmap-tasks-*)"
keywords = ["jmap", "tasks", "types", "rfc8620"]
categories = ["encoding", "network-programming"]

[dependencies]
jmap-jscalendar-types = { workspace = true }
jmap-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
