[package]
name = "jmap-cid-types"
version = "0.1.1"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "JMAP Blob Content Identifiers extension data types (draft-atwood-jmap-cid-00)"
keywords = ["jmap", "cid", "sha256", "blob", "types"]
categories = ["encoding", "network-programming"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
