[package]
name = "jmap-mail-types"
version = "0.1.2"
authors.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "RFC 8621 JMAP for Mail data types (Mailbox, Thread, Email, Identity, EmailSubmission, SearchSnippet)"
keywords = ["jmap", "email", "mail", "types", "rfc8621"]
categories = ["email", "encoding"]

[features]
mdn = []
sieve = []

[dependencies]
jmap-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
